version: '3.8'

services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: swe642new
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: pradeepdocsummer/backend:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swe642new
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
        db:
          condition: service_healthy

  frontend:
      build: /Users/Pradeep/Desktop/Swe642/docker/frontend/survey-app
      ports:
        - "4200:80"